### ISSUE TITLE
unfolding fails.

### ISSUE THREAD

**Issue by sliptonic** [shaise/FreeCAD_SheetMetal#5]
I have a relatively simple model that fails unfolding.  I'm attaching the model and the error log
Just remove the .zip extension from the project file.

[unfoldfaillog.txt](https://github.com/shaise/FreeCAD_SheetMetal/files/326498/unfoldfaillog.txt)
[foldingbug.fcstd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/326501/foldingbug.fcstd.zip)

**Comment by shaise** [comment]
Hi sliptonic,
Sorry for the late response.
This issue happens when you add folds to an already unfolded sheet, then try to unfold again.
I have fixed this issue, please check.
Do not check it on the file you sent as the unfolded object there is created incorrectly. You will need to redo your work from the initial folded object.
Let me know if it works and close the issue.

**Comment by luzpaz** [comment]
@sliptonic ping

**Comment by luzpaz** [comment]
@sliptonic hard ping :stuck_out_tongue_winking_eye:

**Comment by sliptonic** [comment]
Can't duplicate problem anymore.  Please consider closed.  Thank you and sorry for late response.
